"""Practice-video scripts, batch 3 (videos 21-40). Same tuple shape as practice.LESSONS:
id, slug, hook (on-screen markup, spoken text, size), ideas [(markup, spoken)], steps [text], spoken practice."""

MORE = [
    # ------------------------------------------------------------------ MTS
    ("mts-2-1", "context-window-is-the-workspace",
     ("“The AI is dumb” usually means *you* were vague.", "When the AI seems dumb, it's usually because you were vague.", 100),
     [("A model can only reason over what is in front of it. Treat the context window like a new hire's *first day.*",
       "A model can only reason over what is in front of it. Treat the context window like a new hire's first day. The relevant files, the conventions, the goal, and the things that must not break."),
      ("Curate hard. Burying the signal in dumps hurts as much as *starving* it. Enough to determine the answer, little enough to find it.",
       "Curate hard. Burying the signal under irrelevant dumps degrades output just as surely as starving it. The skill is selection.")],
     ["Take a task an AI recently did poorly for you.",
      "Rewrite the request with curated context: goal, constraints, examples, relevant code.",
      "Compare the results side by side."],
     "Your practice. Take a task an AI recently did poorly for you. Rewrite the request with curated context. Goal, constraints, examples, and relevant code. Then compare the results side by side."),
    ("mts-3-1", "tools-not-chat",
     ("An agent is a model in a *loop* with tools.", "An agent is a model in a loop with tools.", 108),
     [("It reads state, decides, acts, observes, and repeats. The quality of an agent is mostly the quality of its *tools.*",
       "It reads state, decides, acts, observes the result, and repeats. The quality of an agent is mostly the quality of its tools."),
      ("Small, well-named actions with honest error messages. Start *embarrassingly small:* one agent, three tools, one job.",
       "Small, well named, well described actions, with crisp inputs and honest error messages. Start embarrassingly small. One agent, three tools, one job.")],
     ["Build a single-purpose agent with at most three tools.",
      "Give it one real task you do every week.",
      "Run it ten times. Log every failure and its cause."],
     "Your practice. Build a single purpose agent with no more than three tools that completes one real task you do weekly. Run it ten times, and log every failure and its cause."),
    ("mts-4-3", "reviewing-machine-written-code",
     ("Never approve a diff you can't *explain.*", "Never approve a diff you wouldn't be able to explain line by line.", 108),
     [("Machines don't get tired. But they confidently *invent APIs,* silently drop requirements, and handle errors that can't happen.",
       "The machine does not get tired or skip the boring parts. But it confidently invents APIs, silently drops requirements, and handles errors that can never happen, while missing the one that will."),
      ("Review for *intent* first. Then for the tells: unverified assumptions, dead code dressed as robustness, tests that assert the bug.",
       "Review for intent first. Does this do what was asked? Then look for the classic tells. Unverified assumptions, dead code dressed as robustness, and tests that assert the bug.")],
     ["Have an AI implement a small feature.",
      "Review the diff with a written checklist: requirements covered, APIs verified to exist.",
      "Check errors are handled honestly, and tests would fail if the feature broke."],
     "Your practice. Have an AI implement a small feature. Then review the diff with a written checklist. Requirements covered, APIs verified to exist, errors handled honestly, and tests that would fail if the feature broke."),
    ("mts-5-1", "the-one-day-prototype",
     ("“Would this work?” Not a meeting. A *prototype.*", "Would this work? The answer is almost never a meeting. It's a prototype by tomorrow morning.", 100),
     [("AI collapsed the cost of finding out. Cut the idea down to its *riskiest assumption.* Build only what tests it. Fake the rest.",
       "A I collapsed the cost of finding out. The skill is scoping. Cut the idea down to the single riskiest assumption, build only what tests it, and fake everything else."),
      ("A prototype is a *question,* not a product. It succeeds by producing an answer, even when the answer is no.",
       "A prototype is a question, not a product. It succeeds by producing an answer, even when the answer is no.")],
     ["Pick an idea you've debated for over a month.",
      "Name its riskiest assumption.",
      "Build the smallest thing that tests it, in one day."],
     "Your practice. Pick an idea you've debated for over a month. Define its riskiest assumption. Then build the smallest thing that tests it, in one day, using every AI tool you have."),
    # --------------------------------------------------------------- AGENCY
    ("agency-1-3", "owning-outcomes-not-tasks",
     ("“I sent the email.” Or: “They haven't replied, so I'm *calling.*”", "I sent the email. Or: they haven't replied, so I'm calling tomorrow.", 88),
     [("A task-owner does what was asked and stops. An *outcome-owner* asks what the task was for.",
       "A task owner does what was asked and stops. An outcome owner asks what the task was for, notices when it won't achieve it, and changes course."),
      ("Task ownership is what got automated. *Outcome ownership* is the remaining job. Hold a few outcomes so completely nobody has to check.",
       "In an A I saturated workplace, task ownership is precisely what got automated. Outcome ownership is the remaining job. Hold a few outcomes so completely that nobody behind you needs to check.")],
     ["For each responsibility, name the outcome it serves in one sentence.",
      "Find one place where finishing the task would still fail the outcome.",
      "Fix the gap, not the task."],
     "Your practice. For each of your current responsibilities, name the outcome it serves in one sentence. Find one place where completing the task would still fail the outcome. And fix the gap, not the task."),
    ("agency-3-1", "the-leverage-audit",
     ("Half your week is probably *low leverage.*", "Most professionals spend half their week on low leverage work.", 104),
     [("Rank everything by output per hour of *you.* Decisions, designs, relationships, and systems that run without you sit on top.",
       "Rank everything you do by output per hour of you. At the top, decisions, designs, relationships, and anything that runs without you afterward. At the bottom, work a machine could do, done by hand, again."),
      ("Low-leverage work *feels* productive. High-leverage work feels like procrastinating. One hour on a reusable system can beat a week of tasks.",
       "Low leverage work feels productive, and high leverage work feels like procrastinating. One hour building a reusable system routinely outproduces a week of conscientious task doing.")],
     ["Log your hours for three days in thirty-minute blocks.",
      "Score each block one to ten on leverage.",
      "Eliminate, automate, or delegate the lowest three hours. Permanently."],
     "Your practice. Log your work hours for three days, in thirty minute blocks. Score each block from one to ten on leverage. Then eliminate, automate, or delegate the lowest three hours, permanently."),
    ("agency-5-1", "saying-no-is-leadership",
     ("The slow maybe destroys more trust than a hundred clean *nos.*", "The slow maybe destroys more trust than a hundred clean no's.", 92),
     [("Every yes spends your scarcest resource: *focused attention.* High-agency people are the ones whose few yeses actually happen.",
       "Every yes is a budget allocation of the scarcest resource you have, focused attention. High agency people are the ones whose few yeses actually happen."),
      ("A good no is *fast,* honest about the reason, and offers the smaller thing you can do. When everything is possible, refusing most of it is the whole game.",
       "A good no is fast, honest about the reason, and offers the smaller thing you can do where possible. A I abundance makes this harder. When everything is possible, refusing most of it is the whole game.")],
     ["Find one commitment you're failing slowly.",
      "Convert it this week into a real yes: scheduled and resourced.",
      "Or into a clean no, with an honest explanation."],
     "Your practice. Find one commitment you are currently failing slowly. Convert it this week into either a real yes, scheduled and resourced, or a clean no with an honest explanation."),
    ("agency-6-3", "finishing",
     ("AI made starting effortless. *Finishing* got rare.", "A I made starting effortless. Which made finishing rarer, and more valuable.", 104),
     [("The graveyard of eighty-percent-done projects is where leverage goes to die. *All the cost, none of the compounding.*",
       "The graveyard of eighty percent done projects is where leverage goes to die. All of the cost, none of the compounding."),
      ("Finishing is a distinct skill: close scope, do the *unglamorous last mile,* and call it done out loud so it can start paying you back.",
       "Finishing is a distinct skill. Close scope instead of opening it, do the unglamorous last mile, the docs, the migration, the announcement, and call the thing done out loud so it can start paying you back.")],
     ["Inventory your eighty-percent-done projects.",
      "Kill half of them explicitly: written, announced, archived.",
      "Finish one completely within two weeks."],
     "Your practice. Inventory your eighty percent done projects. Kill half of them explicitly. Written, announced, archived. Then finish one completely within two weeks, and notice which felt harder."),
    # ---------------------------------------------------------------- TASTE
    ("taste-1-1", "taste-is-judgment",
     ("“I like it” is preference. Taste comes with *reasons.*", "I like it, is preference. Taste comes with reasons.", 100),
     [("“This works because the hierarchy guides your eye to the one action that matters.” That's *taste.* Arguable, teachable, valuable.",
       "This works because the hierarchy guides your eye to the one action that matters. That is taste. Preference is private and arbitrary. Taste is arguable, teachable, and therefore valuable."),
      ("You can't practice having better feelings. You can practice connecting what you feel to *why.* That loop is the whole education.",
       "You cannot practice having better feelings. You can absolutely practice connecting what you feel to why. Run that loop thousands of times, and that is the entire education.")],
     ["Pick one product you love and one you find ugly.",
      "Write five sentences of reasons for each. No “I like,” no “it feels.”",
      "Every claim must point at something concrete on the screen."],
     "Your practice. Pick one product you love and one you find ugly. For each, write five sentences of reasons. No, I like, no, it feels. Every claim must reference something concrete on the screen."),
    ("taste-2-1", "noticing-the-slow-look",
     ("Generated mediocrity survives the *fast look.*", "A I output is engineered to survive the fast look.", 108),
     [("Most looking is recognition: a tenth of a second of “landing page.” *Seeing* is slower. Where does the eye land first? Was that chosen?",
       "Most looking is recognition. A tenth of a second of, landing page, and the mind moves on. Seeing is slower. Where does the eye land first, and was that chosen? What is aligned to what?"),
      ("Plausible at a glance, sloppy under attention. That's the signature of *generated* work. The slow look is your quality control.",
       "Plausible at a glance, sloppy under attention. That is the signature of generated mediocrity. The slow look is your quality control instrument.")],
     ["Choose one screen you use daily.",
      "Look at it for ten full minutes.",
      "Write twenty observations: things that are actually there, not judgments."],
     "Your practice. Choose one screen you use daily and look at it for ten full minutes. Write down twenty observations. Things that are actually there, not judgments. The last five will be the interesting ones."),
    ("taste-3-2", "space-is-a-material",
     ("Whitespace isn't waste. It's the *material.*", "Whitespace isn't waste. It's the most expressive material you have.", 110),
     [("Space groups without boxes, separates without lines, and confers importance without size. Related things sit *close.* Unrelated things sit measurably farther.",
       "Space is how you group without boxes, separate without lines, and confer importance without size. Related things sit close. Unrelated things sit measurably farther apart."),
      ("Use the same handful of gaps everywhere. Rhythm comes from *repetition,* calm from rhythm. The hard part is deciding what to cut.",
       "The spacing system repeats. The same handful of gaps everywhere, never a new value invented on the spot. Rhythm comes from repetition, and calm comes from rhythm. The hard part of whitespace is the decision about what to cut.")],
     ["Audit one of your layouts. List every distinct spacing value.",
      "Reduce the list to four values on a consistent scale.",
      "Rebuild, and notice what the discipline does to the page."],
     "Your practice. Audit one of your layouts and list every distinct spacing value in it. Reduce the list to four values on a consistent scale, and rebuild. Watch what the discipline does to the feeling of the page."),
    ("taste-5-2", "knowing-when-its-done",
     ("Done is when the remaining changes are *preferences.*", "The work is done when the remaining changes are preferences, not improvements.", 96),
     [("Ship early and you leave the rough edge every user feels. Polish forever and you hide *fear of judgment* behind craftsmanship.",
       "Shipping early leaves the rough edge every user feels and nobody reports. Polishing forever hides fear of judgment behind craftsmanship."),
      ("Before shipping, one full pass as a *stranger.* Fresh eyes, real device. Fix what snags. Ignore what is merely different from how you'd do it. Ship.",
       "Before shipping, do one full pass as a stranger. Fresh eyes, real device. Fix what genuinely snags. Ignore what is merely different from how you'd do it today. Then ship.")],
     ["Before you start, write the definition of done: the three things it must achieve.",
      "When they're met, do one stranger's pass.",
      "Ship, even though you can see five more tweaks."],
     "Your practice. On your next piece of work, write the definition of done before you start. The three things it must achieve. When they're met, do one stranger's pass and ship, even though you can see five more tweaks. Especially because you can."),
    # ---------------------------------------------------------- RELATIONSHIPS
    ("rel-3-3", "follow-through-as-a-system",
     ("Most relationships don't end. They *evaporate.*", "Most relationships don't end. They evaporate.", 118),
     [("Nobody followed up, and eighteen months later you're strangers again. The fix is unromantic: a *system.* A ledger of who matters and when to resurface.",
       "Nobody followed up, and eighteen months later you are strangers again. The fix is unromantic. A system. A simple ledger of people who matter, what was last said, what you promised, and when to resurface."),
      ("AI can draft and remind. The *warmth* must be yours. Resurface helpfully, twice a year, with no agenda, and you become the first call.",
       "A I is the perfect assistant for drafting check ins and reminding you it has been a quarter. The warmth must be yours; the reliability can be engineered. Resurface helpfully twice a year, with no agenda, and you become the first call when the big need appears.")],
     ["Build your ledger: twenty-five names, last contact, open promises, next touch date.",
      "Set up an AI-assisted reminder loop.",
      "Send the three most overdue check-ins. Helpful, zero asks."],
     "Your practice. Build your relationship ledger this week. Twenty five names, last contact, open promises, next touch date. Set up the A I assisted reminder loop. Then send the three most overdue check ins. Genuinely helpful, zero asks."),
    ("rel-4-1", "selling-is-helping",
     ("“I don't think we're the right fit. Here's who *is.*”", "I don't think we're the right fit for this. Here's who is.", 100),
     [("Sales isn't persuasion. It's finding people with a problem you genuinely solve and making it *easy to choose you* when you're right.",
       "Sales is the process of finding people with a problem you genuinely solve, helping them understand their options, and making it easy to choose you when you are the right choice."),
      ("That sentence loses the deal and wins the *decade.* Every honest non-sale is marketing. Every oversold customer is a time bomb.",
       "That sentence loses the deal, and wins the decade. In a trust scarce market, every honest non sale is marketing, and every oversold customer is a time bomb in your reputation.")],
     ["Write your honest fit description: who you help brilliantly, who adequately.",
      "And who you should send elsewhere, with names of where.",
      "Use it out loud in your next real sales conversation."],
     "Your practice. Write your honest fit description. Who you help brilliantly, who you help adequately, and who you should send elsewhere, with names of where to send them. Use it in your next real sales conversation, out loud."),
    ("rel-5-1", "give-first",
     ("Generosity signals *abundance.* Abundance attracts opportunity.", "Generosity signals abundance, and abundance attracts opportunity.", 98),
     [("The introduction that costs two minutes and changes someone's year. The candid answer. Help *before* there's anything in it for you.",
       "The strongest networks are built by people who help before there is anything in it for them. The introduction that costs you two minutes and changes someone's year. The candid answer to, how did you solve this?"),
      ("Scorekeeping kills it. *Sincerity* compounds. AI lowered the cost: an analysis, a tool, a research summary in an hour. Most people still won't bother.",
       "Scorekeeping kills it; sincerity compounds. A I raises the ceiling on generosity. You can produce something genuinely useful for someone in an hour. The cost dropped, but the signal survives, because most people still won't bother.")],
     ["Once a week for a month, do one act of unrequested usefulness.",
      "An intro, a resource, or an hour of your expertise.",
      "Track nothing. Check what came back in six months."],
     "Your practice. Once a week for the next month, do one act of unrequested usefulness for someone in your network. An intro, a resource, an hour of your expertise. Track nothing. Notice, six months from now, what came back."),
    ("rel-6-1", "negotiation-without-poker-faces",
     ("Folk negotiation is bluffing. Durable negotiation is *curiosity.*", "Folk negotiation is bluffing. Durable negotiation is curiosity.", 94),
     [("Know what you *need.* Know your real alternative. Then ask what they actually value, which is rarely what you value.",
       "Know what you need, not just want. Know your real alternative if this falls through. And ask enough questions to learn what they actually value, which is rarely symmetric with what you value."),
      ("The best deals trade things *cheap for you, precious for them.* Squeeze a partner and you collect the discount now, and the resentment forever.",
       "The best deals trade things cheap for you and precious for them, in both directions. Squeeze a partner brutally and you collect the discount now, and the resentment forever.")],
     ["Before your next negotiation, write three lists: must-haves, nice-to-haves, cheap-for-me-precious-for-them.",
      "Ask five questions before making any offer.",
      "Compare the outcome to your usual approach."],
     "Your practice. For your next real negotiation, write three lists in advance. Must haves, nice to haves, and trades that are cheap for you and precious for them. In the conversation, ask five questions before making any offer. Compare the outcome to your usual approach."),
    # ----------------------------------------------------------------- COMM
    ("comm-1-2", "one-point-sharpened",
     ("Four points compress into *zero.*", "Most failed communication has four points, which the audience compresses into zero.", 120),
     [("Every effective message has exactly one point: the sentence you'd keep if you could keep only one. If you can't say it, you have a *topic,* not a point.",
       "Every effective communication has exactly one point. The sentence you would keep if you could keep only one. If you cannot say your point in one sentence, you do not have a point yet. You have a topic."),
      ("The test: an hour later, what does your audience *repeat to someone else?* That paraphrase is what you actually shipped.",
       "Here is the test. An hour after your communication, what does the audience repeat to someone else? That paraphrase, not your document, is what you actually shipped.")],
     ["Take your last three significant messages: a memo, a deck, a long email.",
      "For each, write the one sentence it existed to convey.",
      "Can't? Rewrite one around a single point and send it."],
     "Your practice. Take your last three significant messages. A memo, a deck, a long email. For each, write the one sentence it existed to convey. If you can't, rewrite one of them around a single point, and send the new version."),
    ("comm-2-2", "editing-for-the-reader",
     ("Half the length is hiding *inside* the draft.", "Half the length is usually hiding inside the draft.", 112),
     [("First drafts are written for the writer. Cut the throat-clearing. Replace abstractions with *specifics.* Delete every word the sentence survives without.",
       "First drafts are written for the writer. Editing converts them into something written for the reader. Cut the throat clearing opening, replace abstractions with specifics, and delete every word the sentence survives without."),
      ("Read it aloud: the ear catches what the eye *forgives.* And edit for the skimmer. Everyone is one.",
       "Read it aloud. The ear catches what the eye forgives. And edit for the skimmer too, because everyone is one. A document has to work at three speeds. Glance, skim, and study.")],
     ["Take six hundred words you've written.",
      "Cut to three hundred without losing a single necessary idea.",
      "Have AI try the same cut. Note what it couldn't know to keep."],
     "Your practice. Take six hundred words you've written and cut to three hundred, without losing a single necessary idea. Then have A I attempt the same cut, compare its choices to yours, and note what it couldn't know to keep."),
    ("comm-4-1", "model-the-head",
     ("Your audience is not you with *less information.*", "Your audience is not you with less information.", 110),
     [("Four questions before any message that matters: what do they *know?* What do they *care* about? What do they *fear?* What do I *need* from them?",
       "Before any consequential communication, answer four questions about the receiving mind. What do they already know? What do they actually care about? What do they fear? And what do I need from them?"),
      ("The CFO hears “exciting technology” as *unbudgeted risk.* AI knows the general audience. You know this VP was burned by exactly this project.",
       "The CFO hears exciting technology as unbudgeted risk. The machine knows the general audience, but you know that this particular V P was burned by exactly this kind of project two years ago.")],
     ["Before your next significant message, write four answers: knows, cares, fears, needed.",
      "Then write the message.",
      "After the reply, score your model against reality."],
     "Your practice. For your next significant message, write the four answers first. Knows, cares, fears, needed. Then write the message. File both, and after the response arrives, score your model against reality."),
    ("comm-6-2", "feedback-that-lands",
     ("“You're careless” is an attack. A *fact* is information.", "You're careless, is an attack. The last two releases shipped without the checklist, is information.", 94),
     [("Say what happened, the impact it had, and what different would look like. Close to the event, in private, assuming they want to be *good.*",
       "Be specific, behavioral, and prompt. What happened, observable and not interpreted. The impact it had. And what different would look like. Deliver it close to the event, in private, assuming the person wants to be good at their job."),
      ("Receiving is the rarer skill. Ask for the example. Resist the rebuttal for *one full day.* Say thank you, even when it stings.",
       "Receiving is the same skill reversed, and the rarer one. Ask for the example, resist the rebuttal for one full day, and thank the giver even when it stings. The alternative is a future where no one tells you anything.")],
     ["Deliver one piece of real feedback: what happened, the impact, what different looks like.",
      "Ask a colleague: “what's one thing I do that makes your work harder?”",
      "Say thank you. Sit with it for a day."],
     "Your practice. Deliver one piece of real feedback this week, in the what, impact, different form. And ask for one. Ask a colleague, what's one thing I do that makes your work harder? Then just say thank you, and sit with it for a day."),
]
